### ISSUE TITLE
TypeError: Object #<Object> has no method 'getPreparedTitle'

### ISSUE THREAD

**Issue by asdofindia** [docpad/docpad-plugin-partials#25]
What I did:
* Updated the local docpad (which was generated from generator-docpad) from 6.56.0 to 6.69.2
* It was not working immediately.
* So I removed package.json and node_modules directory and started installing local docpad from scratch
* I installed all my plugins **except** docpad-plugin-partials and `docpad run` works fine generating content.
* `docpad install partials`
* Insert code for partials
```
<%- @partial('favicon', false) %>
```
* `docpad run`  produced a long list of errors with no method 'getPreparedTitle'
Here is a sample:
```
TypeError: Object #<Object> has no method 'getPreparedTitle'
  at Object.eval (<anonymous>:43:34)
  at Object.eval (<anonymous>:157:8)
  at eval (<anonymous>:159:6)
  at Function.eco.render (/home/akshay/project/node_modules/docpad-plugin-eco/node_modules/eco/lib/index.js:26:25)
  at EcoPlugin.render (/home/akshay/project/node_modules/docpad-plugin-eco/out/eco.plugin.js:23:32)
  at ambi (/home/akshay/project/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:57:27)
  at Task.<anonymous> (/home/akshay/project/node_modules/docpad/node_modules/event-emitter-grouped/out/lib/event-emitter-grouped.js:45:23)
  at ambi (/home/akshay/project/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:55:18)
  at fire (/home/akshay/project/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:384:27)
  at b (domain.js:183:18)
  at Domain.run (domain.js:123:23)
  at Task.fire (/home/akshay/project/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:398:25)
  at Object._onImmediate (/home/akshay/project/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:414:26)
  at processImmediate [as _immediateCallback] (timers.js:354:15)
```
```
$ docpad --version 
v6.69.2 (local installation: /home/akshay/project/node_modules/docpad)
$ node --version
v0.10.35
$ npm --version
2.1.17
```
Operating system: Arch linux, 64 bit

Here is a comparison of all that changed: https://github.com/learnlearnin/learnlearnin.github.io/compare/cc83b21...fddc473

**Comment by asdofindia** [comment]
I am absolutely sorry, this was because of a line I added to docpad.coffee
```
collections:
    posts: -> @getCollection("html").findAllLive().on "add", (model) -> model.setMetaDefaults({layout: "default"})
```
https://github.com/learnlearnin/learnlearnin.github.io/blob/0efc8c94a4cea7bf86d16246e5279c02099aaac5/docpad.coffee#L40

---

In case you know a better way to set a default layout for all my files in documents, do let me know.
